# Profile Author: Zer0-hex
[[Tool]]
Name = "Peass-ng"
Tag = "shareApp"
Url = "https://github.com/carlospolop/PEASS-ng/releases/latest"
Files = [
    "linpeas.sh",
    "linpeas_darwin_amd64",
    "linpeas_darwin_arm64",
    "linpeas_fat.sh",
    "linpeas_linux_386",
    "linpeas_linux_amd64",
    "linpeas_linux_arm",
    "linpeas_linux_arm64",
    "winPEAS.bat",
    "winPEASany.exe",
    "winPEASany_ofs.exe",
    "winPEASx64.exe",
    "winPEASx64_ofs.exe",
    "winPEASx86.exe",
    "winPEASx86_ofs.exe",
]
Action = "cp DIRPATH TAG/NAME"

[[Tool]]
Name = "mimikatz"
Tag = "shareApp"
Url = "https://github.com/gentilkiwi/mimikatz/releases/latest"
Files = [
    "mimikatz_trunk.7z",
]
Action = "7z x FILEPATH -oTAG/NAME"

[[Tool]]
Name = "nishang"
Tag = "shareApp"
Url = "https://github.com/samratashok/nishang/releases/latest"
# https://github.com/samratashok/nishang/archive/refs/tags/v0.7.6.zip
Files = ["master"]
Action = "7z x FILEPATH -oTAG/NAME"

[[Tool]]
Name = "PowerSploit"
Tag = "shareApp"
Url = "https://github.com/PowerShellMafia/PowerSploit/releases/latest"
Files = ["master"]
Action = "7z e FILEPATH -oTAG/NAME"

[[Tool]]
Name = "Rubeus"
Tag = "ADTool"
Url = "https://github.com/GhostPack/Rubeus/releases/latest"
Files = ["master"]
Action = "7z x FILEPATH -oTAG/NAME"


[[Tool]]
Name = "SharpHound"
Tag = "shareApp"
Url = "https://github.com/BloodHoundAD/SharpHound/releases/latest"
Files = [
    "SharpHound-VERSION.zip",
]
Action = "7z x FILEPATH -oTAG/NAME"
