# Profile Author: Zer0-hex
[[Tool]]
Name = "Peass-ng"
Tag = "shareApp"
Url = "https://github.com/carlospolop/PEASS-ng/releases/latest"
Files = [
    "linpeas.sh",
    "linpeas_darwin_amd64",
    "linpeas_darwin_arm64",
    "linpeas_fat.sh",
    "linpeas_linux_386",
    "linpeas_linux_amd64",
    "linpeas_linux_arm",
    "linpeas_linux_arm64",
    "winPEAS.bat",
    "winPEASany.exe",
    "winPEASany_ofs.exe",
    "winPEASx64.exe",
    "winPEASx64_ofs.exe",
    "winPEASx86.exe",
    "winPEASx86_ofs.exe",
]

[[Tool]]
Name = "mimikatz"
Tag = "shareApp"
Url = "https://github.com/11111"
Files = [
    "linpeas.sh",
]

[[Tool]]
Name = "BlackArch"
Tag = "webShell"
Url = "https://github.com/BlackArch/webshells"
Files = []

[[Tool]]
Name = "Kali"
Tag = "webShell"
Url = "https://github.com/kali"
Files = []